In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data/spam.csv', encoding='latin-1')

In [5]:
df.shape

(5572, 5)

In [6]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [7]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [8]:
to_drop=['Unnamed: 2','Unnamed: 2','Unnamed: 3','Unnamed: 4']
df=df.drop(columns=to_drop)

In [9]:
#lower case the messagese
df['v2']=df['v2'].str.lower()
df['v2']

0       go until jurong point, crazy.. available only ...
1                           ok lar... joking wif u oni...
2       free entry in 2 a wkly comp to win fa cup fina...
3       u dun say so early hor... u c already then say...
4       nah i don't think he goes to usf, he lives aro...
                              ...
5567    this is the 2nd time we have tried 2 contact u...
5568                will ì_ b going to esplanade fr home?
5569    pity, * was in mood for that. so...any other s...
5570    the guy did some bitching but i acted like i'd...
5571                           rofl. its true to its name
Name: v2, Length: 5572, dtype: str

In [10]:
#remove punctuation marks
import re 
df['v2']=df['v2'].apply(lambda x: re.sub(r"[^\w\s]", "", x))

In [11]:
df['v2']

0       go until jurong point crazy available only in ...
1                                 ok lar joking wif u oni
2       free entry in 2 a wkly comp to win fa cup fina...
3             u dun say so early hor u c already then say
4       nah i dont think he goes to usf he lives aroun...
                              ...
5567    this is the 2nd time we have tried 2 contact u...
5568                 will ì_ b going to esplanade fr home
5569    pity  was in mood for that soany other suggest...
5570    the guy did some bitching but i acted like id ...
5571                            rofl its true to its name
Name: v2, Length: 5572, dtype: str

In [12]:
#apply tokenisation and remove stop words
import nltk 
nltk.download("stopwords")
nltk.download("punkt")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\youss\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\youss\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [13]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [14]:
stop_words=stopwords.words("english")
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\youss\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\youss\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\youss\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
df['v2']=df['v2'].apply(word_tokenize)

In [16]:
df

        v1                                                 v2
0      ham  [go, until, jurong, point, crazy, available, o...
1      ham                     [ok, lar, joking, wif, u, oni]
2     spam  [free, entry, in, 2, a, wkly, comp, to, win, f...
3      ham  [u, dun, say, so, early, hor, u, c, already, t...
4      ham  [nah, i, dont, think, he, goes, to, usf, he, l...
...    ...                                                ...
5567  spam  [this, is, the, 2nd, time, we, have, tried, 2,...
5568   ham      [will, ì_, b, going, to, esplanade, fr, home]
5569   ham  [pity, was, in, mood, for, that, soany, other,...
5570   ham  [the, guy, did, some, bitching, but, i, acted,...
5571   ham                   [rofl, its, true, to, its, name]

[5572 rows x 2 columns]

In [17]:
def remove_stop_words(tokens) :
    return [word for word in tokens if word not in stop_words]

In [18]:
df.apply(remove_stop_words)

        v1                                                 v2
0      ham  [go, until, jurong, point, crazy, available, o...
1      ham                     [ok, lar, joking, wif, u, oni]
2     spam  [free, entry, in, 2, a, wkly, comp, to, win, f...
3      ham  [u, dun, say, so, early, hor, u, c, already, t...
4      ham  [nah, i, dont, think, he, goes, to, usf, he, l...
...    ...                                                ...
5567  spam  [this, is, the, 2nd, time, we, have, tried, 2,...
5568   ham      [will, ì_, b, going, to, esplanade, fr, home]
5569   ham  [pity, was, in, mood, for, that, soany, other,...
5570   ham  [the, guy, did, some, bitching, but, i, acted,...
5571   ham                   [rofl, its, true, to, its, name]

[5572 rows x 2 columns]

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\youss\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [20]:
lemmatizer = WordNetLemmatizer()

In [21]:
def lem(tokens) :
    return [lemmatizer.lemmatize(word) for word in tokens]

In [22]:
df['v2'].apply(lem)

0       [go, until, jurong, point, crazy, available, o...
1                          [ok, lar, joking, wif, u, oni]
2       [free, entry, in, 2, a, wkly, comp, to, win, f...
3       [u, dun, say, so, early, hor, u, c, already, t...
4       [nah, i, dont, think, he, go, to, usf, he, lif...
                              ...
5567    [this, is, the, 2nd, time, we, have, tried, 2,...
5568        [will, ì_, b, going, to, esplanade, fr, home]
5569    [pity, wa, in, mood, for, that, soany, other, ...
5570    [the, guy, did, some, bitching, but, i, acted,...
5571                       [rofl, it, true, to, it, name]
Name: v2, Length: 5572, dtype: object

In [23]:
df

        v1                                                 v2
0      ham  [go, until, jurong, point, crazy, available, o...
1      ham                     [ok, lar, joking, wif, u, oni]
2     spam  [free, entry, in, 2, a, wkly, comp, to, win, f...
3      ham  [u, dun, say, so, early, hor, u, c, already, t...
4      ham  [nah, i, dont, think, he, goes, to, usf, he, l...
...    ...                                                ...
5567  spam  [this, is, the, 2nd, time, we, have, tried, 2,...
5568   ham      [will, ì_, b, going, to, esplanade, fr, home]
5569   ham  [pity, was, in, mood, for, that, soany, other,...
5570   ham  [the, guy, did, some, bitching, but, i, acted,...
5571   ham                   [rofl, its, true, to, its, name]

[5572 rows x 2 columns]